apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crazy-train-demo
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/Demo-AI-Edge-Crazy-Train/gitops.git
    targetRevision: main
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
