apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  generateName: train-ceq-app-
spec:
  pipelineRef:
    name: quarkus-multiarch
  params:
  - name: git-url
    value: https://github.com/Demo-AI-Edge-Crazy-Train/train-ceq-app
  - name: git-revision
    value: main
  - name: image-name
    value: quay.io/demo-ai-edge-crazy-train/train-ceq-app
  - name: context-dir
    value: .
  - name: containerfile-path
    value: src/main/docker/Dockerfile.jvm
  workspaces:
  - name: oci-images
    volumeClaimTemplate:
      spec:
        storageClassName: efs-csi
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
  - name: sources
    volumeClaimTemplate:
      spec:
        storageClassName: efs-csi
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
  - name: registry-token
    secret:
      secretName: quay-authentication
  - name: maven-settings
    emptyDir: {}
  taskRunSpecs:
  - pipelineTaskName: maven-package-aarch64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      tolerations:
      - key: "emea-open-demo.redhat.com/arm64-architecture"
        operator: "Exists"
        effect: "NoSchedule"
  - pipelineTaskName: build-aarch64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      tolerations:
      - key: "emea-open-demo.redhat.com/arm64-architecture"
        operator: "Exists"
        effect: "NoSchedule"
  taskRunTemplate:
    serviceAccountName: buildbot
