apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  generateName: train-monitoring-app-
spec:
  pipelineRef:
    name: quarkus-multiarch
  params:
  - name: git-url
    value: https://github.com/Demo-AI-Edge-Crazy-Train/train-monitoring-app
  - name: git-revision
    value: main
  - name: image-name
    value: quay.io/demo-ai-edge-crazy-train/train-monitoring-app
  - name: context-dir
    value: monitoring-app
  - name: containerfile-path
    value: monitoring-app/src/main/docker/Dockerfile.jvm
  workspaces:
  - name: oci-images
    volumeClaimTemplate:
      spec:
        storageClassName: efs-csi
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
  - name: sources
    volumeClaimTemplate:
      spec:
        storageClassName: efs-csi
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
  - name: registry-token
    secret:
      secretName: quay-authentication
  - name: maven-settings
    configMap:
      name: maven-settings
  taskRunSpecs:
  - pipelineTaskName: maven-package-x86-64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
  - pipelineTaskName: maven-package-aarch64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
  - pipelineTaskName: build-x86-64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
  - pipelineTaskName: build-aarch64
    podTemplate:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
  taskRunTemplate:
    serviceAccountName: buildbot
