apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: operating-center
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      replica.fetch.max.bytes: 3145728
      message.max.bytes: 3145728
      auto.create.topics.enable: true
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        type: route
        tls: true
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        type: loadbalancer
        tls: false
    version: 4.0.0
    metadataVersion: '4.0'
    rack:
      topologyKey: topology.kubernetes.io/zone
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: default-pool
  labels:
    strimzi.io/cluster: operating-center
spec:
  replicas: 3
  roles:
  - controller
  - broker
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: operating-center
  name: train
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: train-user
    type: scram-sha-512
---
apiVersion: v1
stringData:
  password: R3dH4t1!
kind: Secret
metadata:
  name: train-user
type: Opaque
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: operating-center
  name: kafdrop
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: kafdrop-user
    type: scram-sha-512
---
apiVersion: v1
stringData:
  password: R3dH4t1!
kind: Secret
metadata:
  name: kafdrop-user
type: Opaque
