apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: operating-center
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.9.0'
      replica.fetch.max.bytes: 3145728
      message.max.bytes: 3145728
    storage:
      type: ephemeral
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        type: internal
        tls: false
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        type: route
        tls: true
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        type: loadbalancer
        tls: false
    version: 3.9.0
    metadataVersion: '3.9'
    replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: operating-center
  name: train
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: train-user
    type: scram-sha-512
---
apiVersion: v1
stringData:
  password: R3dH4t1!
kind: Secret
metadata:
  name: train-user
type: Opaque
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: operating-center
  name: kafdrop
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: kafdrop-user
    type: scram-sha-512
---
apiVersion: v1
stringData:
  password: R3dH4t1!
kind: Secret
metadata:
  name: kafdrop-user
type: Opaque
