kind: Secret
apiVersion: v1
metadata:
  name: kafdrop-kafka-config
  labels:
    app.kubernetes.io/instance: kafdrop
    app.kubernetes.io/name: kafdrop
stringData:
  kafka.properties: |
    security.protocol=PLAINTEXT
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafdrop" password="R3dH4t1!"
type: Opaque
