apiVersion: v2
name: train
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
