{{ if has "ci-pipelines" .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-pipelines
  namespace: openshift-gitops
spec:
  project: crazy-train-demo
  source:
    repoURL: https://github.com/Demo-AI-Edge-Crazy-Train/gitops.git
    targetRevision: main
    path: ci-pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-pipelines
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
{{ end }}
