{{ if has "kafdrop" .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: openshift-gitops
spec:
  project: crazy-train-demo
  sources:
  - repoURL: https://github.com/obsidiandynamics/kafdrop.git
    targetRevision: "4.0.1"
    path: chart
    helm:
      valuesObject:
        kafka:
          brokerConnect: operating-center-kafka-bootstrap.operating-center.svc.cluster.local:9092
        server:
          servlet:
            contextPath: /
        jvm:
          opts: "-Xms32M -Xmx64M"
        image:
          tag: "4.0.1"
        service:
          type: "ClusterIP"
        nodeSelector:
          kubernetes.io/arch: amd64
  - repoURL: https://github.com/Demo-AI-Edge-Crazy-Train/gitops.git
    targetRevision: main
    path: kafdrop
  destination:
    server: https://kubernetes.default.svc
    namespace: kafdrop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
{{ end }}
