apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crazy-train-demo
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Demo-AI-Edge-Crazy-Train/gitops.git
