apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildbot
  namespace: {{ .Values.namespace | quote }}
#imagePullSecrets:
#- name: quay-authentication
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildbot-scc
  namespace: {{ .Values.namespace | quote }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildbot-scc
  namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildbot-scc
subjects:
- kind: ServiceAccount
  name: buildbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildbot-is-eventlistener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
subjects:
- kind: ServiceAccount
  name: buildbot
  namespace: {{ .Values.namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildbot-is-eventlistener
  namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
subjects:
- kind: ServiceAccount
  name: buildbot
