replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: localhost:9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "kafka.properties"
  truststoreFile: "kafka.truststore.jks"
  keystoreFile: "kafka.keystore.jks"
  configSecretName: ""

host:

jvm:
  opts: "-Xms2048M -Xmx2048M"
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: ""

global:
  kubeVersion: ~

server:
  port: 9000
  servlet:
    contextPath: /

service:
  annotations: {}
  type: ClusterIP
  port: 9000
  nodePort: 30900

ingress:
  enabled: false
  annotations: {}
  apiVersion: ~
  #ingressClassName: ~
  path: /
  #pathType: ~
  hosts: []
  tls: []

route:
  enabled: true

resources:
  limits:
   cpu: 1
   memory: 2048Mi
  requests:
    cpu: 300m
    memory: 2048Mi

nodeSelector:
  kubernetes.io/arch: amd64

tolerations: []

affinity: {}

podAnnotations: {}

hostAliases: []

mountProtoDesc: 
  enabled: false
  hostPath: