apiVersion: v1
kind: ConfigMap
metadata:
  name: capture-app-env
  namespace: {{ .Values.global.namespace | quote }}
data:
  VIDEO_DEVICE_INDEX: "0"
  TMP_FOLDER: "/tmp"
  INTERVAL: "100"
  NB_IMAGE_SEC: "10"
  MQTT_BROKER: "tcp://mosquitto:1883"
  MQTT_TOPIC: "train-image"
  SAVE_IMAGE: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capture-app-data
  namespace: {{ .Values.global.namespace | quote }}
spec:
  storageClassName: topolvm-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capture-app
    app.kubernetes.io/component: capture-app
    app.kubernetes.io/instance: capture-app
    app.kubernetes.io/name: capture-app
    app.kubernetes.io/part-of: train
  name: capture-app
  namespace: {{ .Values.global.namespace | quote }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: capture-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capture-app
        deployment: capture-app
    spec:
      containers:
      - image: {{ template "captureApp.image" . }}
        imagePullPolicy: {{ .Values.captureApp.image.pullPolicy | quote }}
        name: capture-app
        envFrom:
        - configMapRef:
            name: capture-app-env
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /tmp/crazy-images
        - name: dev
          mountPath: /dev
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: train
      serviceAccount: train
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: capture-app-data
      - name: dev
        hostPath:
          path: /dev
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: capture-app
    app.kubernetes.io/component: capture-app
    app.kubernetes.io/instance: capture-app
    app.kubernetes.io/name: capture-app
    app.kubernetes.io/part-of: train
  name: capture-app
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: capture-app
    deployment: capture-app
