apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligent-train-env
  namespace: {{ .Values.global.namespace | quote }}
data:
  MQTT_BROKER: "mosquitto"
  MQTT_PORT: "1883"
  MQTT_TOPIC: "train-image"
  MQTT_PUB_TOPIC: "train-model-result"
  MODEL_PATH: models/model.onnx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intelligent-train
    app.kubernetes.io/component: intelligent-train
    app.kubernetes.io/instance: intelligent-train
    app.kubernetes.io/name: intelligent-train
    app.kubernetes.io/part-of: train
  name: intelligent-train
  namespace: {{ .Values.global.namespace | quote }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: intelligent-train
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: intelligent-train
        deployment: intelligent-train
    spec:
      containers:
      - image: quay.io/demo-ai-edge-crazy-train/intelligent-train:jetson
        imagePullPolicy: {{ .Values.intelligentTrain.image.pullPolicy | quote }}
        name: intelligent-train
        envFrom:
        - configMapRef:
            name: intelligent-train-env
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: train
      serviceAccount: train
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

