{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: {{ .Values.global.namespace | quote }}
spec:
  storageClassName: topolvm-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ template "kafka.image" . }}
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy | quote }}
          ports:
            - containerPort: 9094
              protocol: TCP
            - containerPort: 9093
              protocol: TCP
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9094,CONTROLLER://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.{{ .Values.global.namespace }}.svc.cluster.local:9094
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka.{{ .Values.global.namespace }}.svc.cluster.local:9093
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: /var/lib/kafka/data
          volumeMounts:
            - name: kafka-config
              mountPath: /mnt/shared/config
            - name: kafka-data
              mountPath: /var/lib/kafka/data
            - name: kafka-secrets
              mountPath: /etc/kafka/secrets
            - name: tmp
              mountPath: /tmp
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: train
      serviceAccount: train
      volumes:
        - name: kafka-config
          emptyDir: {}
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
        - name: kafka-secrets
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace | quote }}
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9094
      targetPort: 9094
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
{{- end }}
