{{- if .Values.monitoringApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: monitoring-app
    app.kubernetes.io/name: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: monitoring-app
          image: {{ template "monitoringApp.image" . }}
          imagePullPolicy: {{ .Values.monitoringApp.image.pullPolicy | quote }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.{{ .Values.global.namespace }}.svc.cluster.local:9094
            - name: KAFKA_TOPIC_MONITORING_NAME
              value: train-monitoring
            - name: KAFKA_TOPIC_COMMAND_CAPTURE_NAME
              value: train-command-capture
            - name: BATCH_SIZE
              value: "0"
            - name: LINGER_MS
              value: "0"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
      serviceAccountName: train
      serviceAccount: train
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: monitoring-app
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: monitoring-app
spec:
  selector:
    app: monitoring-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: monitoring-app
  namespace: {{ .Values.global.namespace | quote }}
spec:
  to:
    kind: Service
    name: monitoring-app
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
{{- end }}
